# Generated by Django 5.0.1 on 2024-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='description',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
