# Generated by Django 5.0.1 on 2024-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0002_experiencialaboral_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='pais',
            field=models.CharField(default='Venezuela', max_length=50),
            preserve_default=False,
        ),
    ]
