# Generated by Django 5.0.1 on 2024-02-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0003_experiencialaboral_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='description',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educacion',
            name='pais',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
