# Generated by Django 5.0.1 on 2024-02-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0004_educacion_description_educacion_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausuario',
            name='bio',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='telefono',
            field=models.CharField(default='#', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='url_facebook',
            field=models.CharField(default='#', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='url_github',
            field=models.CharField(default='#', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='url_linkedin',
            field=models.CharField(default='#', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='url_twitter',
            field=models.CharField(default='#', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datausuario',
            name='url_youtube',
            field=models.CharField(default='#', max_length=30),
            preserve_default=False,
        ),
    ]
