# Generated by Django 5.0.1 on 2024-02-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0005_datausuario_bio_datausuario_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='periodo_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='periodo_inicio',
            field=models.IntegerField(),
        ),
    ]
