# Generated by Django 5.0.1 on 2024-02-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurriculum', '0006_alter_experiencialaboral_periodo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='periodo_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='periodo_inicio',
            field=models.IntegerField(),
        ),
    ]
